name: cnc-admin-core-dev
channels:
  - defaults
  - conda-forge
dependencies:
  - alembic
  - bcrypt
  - flake8
  - mypy
  - pip
  - psycopg2
  - pyqt
  - pyserial
  - pytest
  - pytest-cov
  - pytest-mock
  - python-dotenv
  - sqlalchemy
  - watchdog
  - pip:
    - "celery[redis]"
    - celery-types
    - pytest-sqlalchemy-mock
